/* eslint-disable object-curly-newline */
import { Head, Html, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        />
        <link href="https://fonts.googleapis.com/css2?family=Inter" rel="stylesheet" />
      </Head>
      <body style={{ backgroundColor: '#fafafa' }}>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
